---
deployment:
  tasks:
    - export DEPLOY_PATH=/home/$USER/public_html
    - npm ci
    - npm run build
    - rsync -a --delete .next/static/ $DEPLOY_PATH/_next/static/
    - rsync -a --delete public/ $DEPLOY_PATH/
