apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nextjs-service
spec:
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
        - image: your-nextjs-image:latest
          ports:
            - containerPort: 3000
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP  # Changed to ClusterIP for internal access
