name: Deploy to Production

on:
  push:
    branches:
      - dev_nana

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Run start script
      run: npm start

    - name: Deploy to production
      run: |
        echo "Deploying to production..."
        # Add your deployment script here
        echo "Deployment to production completed."
      
    - name: Notify deployment success
      run: |
        echo "Deployment completed successfully!"
        
    - name: Cleanup resources
      run: |
        echo "Cleaning up resources after deployment..."
        # Add your cleanup script here
        echo "Cleanup completed."
